# Homework#2 6 c)
# this exercise was made with the help of my colleague Fabiana Alves.


#Import Librarys
library(igraph)
library(readr)

# Read gml File
file=read_graph("starwars_v.gml",format = "gml")

# read files generated by gephi with the modularity in nodes
edges = read_csv("edgess_StarWars.csv") 
nodes = read_csv("nodes_StarWars.csv")


# Importing the modularity classes
V(file)$color <- nodes$modularity_class+1

# To view the graph and the communities generated by gephi please umcomment the next line
#plot(file, layout = layout_with_fr, edge.label = NA, vertex.label.cex =1, vertex.size = 20, vertex.color=V(file)$color)


# Calculate Modularity

# adjacency matrix
adjacencyMatrix = get.adjacency(file, sparse=FALSE)

# total number of edges
m = gsize(file) 
Communities <- nodes$modularity_class+1

#Variable with the modularity
Modularity = 0

for(i in 1:vcount(file)){
  for(j in 1:vcount(file)){
    
    if(Communities[i]==Communities[j])
        Modularity =Modularity +adjacencyMatrix[i,j] -(degree(file)[i]*degree(file)[j])/(2*m)
  }
}

Modularity = Modularity/(2*m)


print(paste("Modularity of the starwars_v grpah: ",round(Modularity,4)))