# Homework#2 6 c)
# this exercise was made with the help of my colleague Fabiana Alves.


#Import Librarys
library(igraph)
library(readr)

# Read gml File
file=read_graph("starwars_v.gml",format = "gml")

# read files generated by gephi with the modularity in nodes
edges = read_csv("edgess_StarWars.csv") 
nodes = read_csv("nodes_StarWars.csv")


#Function to calculate modularity
modularityCalc<-function(file,Communities){
  
  # adjacency matrix
  adjacencyMatrix = get.adjacency(file, sparse=FALSE)
  
  # total number of edges
  m = gsize(file) 
  Modularity = 0
  
  for(i in 1:vcount(file)){
    for(j in 1:vcount(file)){
      
      if(Communities[i]==Communities[j])
        Modularity =Modularity +adjacencyMatrix[i,j] -(degree(file)[i]*degree(file)[j])/(2*m)
    }
  }
  
  Modularity = Modularity/(2*m)
  V(file)$color <- nodes$modularity_class+1
  
  # To view the graph and the communities generated by gephi please umcomment the next line
  #plot(file, layout = layout_with_fr, edge.label = NA, vertex.label.cex =1, vertex.size = 20, vertex.color=V(file)$color)
  
  
  return(round(Modularity,4))
}


# Calc the communities in file
Communities <- 1:vcount(file)
#modularityCalc(file,Communities)

adjMod=vector()
baseMod=modularityCalc(file,Communities)
size=0
vec=Communities

for(i in 1:length(vec)){
  for( j in i+1:length(vec)){
    if( j<=length(vec)) {
      PartitionAUX = replace(vec,i,j)
      currentMod=  modularityCalc(file,PartitionAUX)
      
      if(currentMod>baseMod){
        BigPartion = PartitionAUX
        BigModularity = currentMod
      }
      
    }
  }
  print(BigModularity)
  
  adjMod[length(adjMod)+1] = BigModularity
  baseMod = BigModularity
  print(BigPartion)
  vec = BigPartion
}


plot(adjMod)






